<?php
namespace FastDog\Content\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Статистика просмотров материалов
 *
 * @package FastDog\Content\Models
 * @version 0.2.0
 * @author Андрей Мартынов <d.g.dev482@gmail.com>
 */
class ContentStatistic extends Model
{
    /**
     * Назнвание таблицы
     *
     * @var string $table
     */
    protected $table = 'content_statistic_views';

    /**
     *
     * @return bool
     */
    public function delete()
    {
        return false; //parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * Получение статистики
     *
     * Метод возвращает 30 последних записей из таблицы статистики с сортировкой по уменьшению времени
     *
     * @param bool $fire_event
     * @return array
     */
    public static function getStatistic($fire_event = true)
    {
        $result = [];
        $items = self::orderBy('created_at', 'desc')->limit(30)->get();
        foreach ($items as $item) {
            $time = ($item->created_at->getTimestamp() * 1000);
            array_push($result, [
                $time, (int) $item->value,
            ]);
        }

        return $result;
    }
}