<?php
/**
 * Created by PhpStorm.
 * User: dg
 * Date: 05.11.2016
 * Time: 0:36
 */

namespace FastDog\Content\Entity;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Статистика просмотров материалов
 *
 * @package FastDog\Content\Entity
 * @version 0.2.0
 * @author Андрей Мартынов <d.g.dev482@gmail.com>
 */
class ContentStatistic extends Model
{
    /**
     * Назнвание таблицы
     *
     * @var string $table
     */
    protected $table = 'content_statistic_views';

    /**
     *
     * @return bool
     */
    public function delete()
    {
        return false; //parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * Полусение статистики
     *
     * Метод возвращает 30 последних записей из таблицы статистики с сортировкой по уменьшению времени
     *
     * @param bool $fire_event
     * @return array
     */
    public static function getStatistic($fire_event = true)
    {
        $result = [];
        $items = self::orderBy('created_at', 'desc')->limit(30)->get();
        foreach ($items as $item) {
            $time = ($item->created_at->getTimestamp() * 1000);
            array_push($result, [
                $time, (int) $item->value,
            ]);
        }

        return $result;
    }


    /**
     * Создание таблицы базы данных
     *
     * Будут созданы таблицы и триггеры:
     * <pre>
     * CREATE TABLE content_statistic_views (
     *          id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     *          value int(11) NOT NULL,
     *          created_at timestamp NULL DEFAULT NULL,
     *          updated_at timestamp NULL DEFAULT NULL,
     *          PRIMARY KEY (id)
     * )
     * </pre>
     *
     * @return void
     */
    public static function createDbSchema()
    {
        if (!Schema::hasTable('content_statistic_views')) {
            Schema::create('content_statistic_views', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('value');
                $table->timestamps();
            });
            DB::statement("ALTER TABLE `content_statistic_views` comment 'Статистика просмотра материалов'");
        }
    }
}